import Head from "next/head"
import Link from "next/link"
import React from "react"

import type { NextPage } from "next"

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col gap-4 justify-center items-center m-0 min-h-screen">
        <h1>404</h1>
        <Link href="/">トップページへ戻る</Link>
      </main>
    </div>
  )
}

export default Home
