import Head from "next/head"
import { useRouter } from "next/router"
import { useEffect, useState } from "react"

import { PokemonCard } from "../components/PokemonParty"

const MemberPage = () => {
  const [party, setParty] = useState<string[]>([])
  const router = useRouter()

  useEffect(() => {
    if (window) {
      const name = window.location.pathname.slice(1)
      const url = `https://navi-poke-api.youuchiharu.workers.dev/?name=${name}`

      fetch(url, {
        mode: "cors",
      })
        .then((res) => res.json())
        .then((res) => res.party)
        .then((party) => {
          if (typeof party === "string") router.push("/404")

          setParty(party)
        })
    }
  }, [])

  return (
    <div>
      <Head>
        <title>Party Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col gap-4 justify-center items-center m-0 min-h-screen">
        {party.map((pokeName) => (
          <PokemonCard key={pokeName} name={pokeName} />
        ))}
      </main>
    </div>
  )
}

export default MemberPage
